### ISSUE TITLE
create command missing template file(s)

### ISSUE THREAD

**Issue by rot26** [cloudmitigator/reflex-cli#77]
There is an error on `reflex create`, cannot find template file.

```sh
reflex --version
reflex, version 0.7.7
```

```sh
reflex create --rule-name new-rule -m NOTIFY -c NewRule
```

```
Generating rule files...
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.7.4/bin/reflex", line 8, in <module>
    sys.exit(cli())
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/reflex_cli/commands/command_create.py", line 59, in cli
    template_generator.create_templates()
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/reflex_cli/rule_template_generator.py", line 32, in create_templates
    self.create_workflow_template()
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/reflex_cli/rule_template_generator.py", line 55, in create_workflow_template
    template = self.template_env.get_template(".github/workflows/release.yaml")
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/username/.pyenv/versions/3.7.4/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .github/workflows/release.yaml
```

Related to #19

**Comment by mcbanderson** [comment]
Looks like `templates/rule_templates/*` aren't being included in the distribution for some reason

**Comment by mcbanderson** [comment]
Looks like we'll need to make some changes to `setup.py` to ensure these files get distributed. This SO post has some possible solutions:
https://stackoverflow.com/questions/27664504/how-to-add-package-data-recursively-in-python-setup-py/27664856
